eq <- data.frame(trt = letters[1:4], .wt = rep(0.25, 4))
vr <- data.frame(trt = letters[1:4], .wt = c(0.5, 0.2, 0.2, 0.1))

prodplot(eq, ~ trt, "vbar")
ggsave("plots/part-vbar-eq.pdf", width = 4, height = 4)
prodplot(vr, ~ trt, "vbar")
ggsave("plots/part-vbar-vr.pdf", width = 4, height = 4)
prodplot(eq, ~ trt, "hbar")
ggsave("plots/part-hbar-eq.pdf", width = 4, height = 4)
prodplot(vr, ~ trt, "hbar")
ggsave("plots/part-hbar-vr.pdf", width = 4, height = 4)

prodplot(eq, ~ trt, "vspline")
ggsave("plots/part-vspline-eq.pdf", width = 4, height = 4)
prodplot(vr, ~ trt, "vspline")
ggsave("plots/part-vspline-vr.pdf", width = 4, height = 4)
prodplot(eq, ~ trt, "hspline")
ggsave("plots/part-hspline-eq.pdf", width = 4, height = 4)
prodplot(vr, ~ trt, "hspline")
ggsave("plots/part-hspline-vr.pdf", width = 4, height = 4)
